### ISSUE TITLE
l10n: Remove "last"

### ISSUE THREAD

**Issue by Valdnet** [datenangebot/health#62]
The word "last" in line: 
https://github.com/datenangebot/health/blob/825aa01f02e52f80a4ff625e141a641c405d59be/src/general/Chart.vue#L79
is not needed at the end of the sentence because it is displayed with:
https://github.com/datenangebot/health/blob/825aa01f02e52f80a4ff625e141a641c405d59be/src/general/Chart.vue#L25-L67

It now looks like this:
_You selected to show only data from the **last** last 12 hours.
You selected to show only data from the **last** last 24 hours._
e.t.c

I propose to change to:
`You selected to show only data from: {range}.`
This method will also solve the variation of the word "last" in a translation in other languages.

**Comment by Gyges88** [comment]
+1 As it avoids ugly duplication issues like shown above for developers not knowing the value of a specific variable as well as unsolvable declination problems for translators.
Maybe this would even be a good candidate for a general rule, i.e. specifying variable-based ranges **inside** the variable instead of **outside**.

**Comment by Valdnet** [comment]
@datenangebot Proposal: 59180c0930579c789bf5d477c6444f150ab34853. If you approve, you can close the issue 😉.
